# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accrual_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/accrual_type.proto*\x84\x01\n\x0b\x41\x63\x63rualType\x12\x18\n\x14\x41\x43\x43RUAL_TYPE_UNKNOWN\x10\x00\x12\x18\n\x14\x41\x43\x43RUAL_TYPE_INVOICE\x10\x01\x12\x1b\n\x17\x41\x43\x43RUAL_TYPE_CORRECTION\x10\x02\x12$\n ACCRUAL_TYPE_TEMPORAL_CORRECTION\x10\x03\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.accrual_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _ACCRUALTYPE._serialized_start=29
  _ACCRUALTYPE._serialized_end=161
# @@protoc_insertion_point(module_scope)
