# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/accruals_aggregate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/accruals_aggregate.proto\"\xe3\x01\n\x11\x41\x63\x63rualsAggregate\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x01\x12\x14\n\x0cincome_count\x18\x03 \x01(\x05\x12\x14\n\x0cincome_total\x18\x04 \x01(\x01\x12\x15\n\routcome_count\x18\x05 \x01(\x05\x12\x15\n\routcome_total\x18\x06 \x01(\x01\x12\x16\n\x0e\x65xchange_count\x18\x07 \x01(\x05\x12\x16\n\x0e\x65xchange_total\x18\x08 \x01(\x01\x12\x12\n\ndebt_count\x18\t \x01(\x05\x12\x12\n\ndebt_total\x18\n \x01(\x01\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.accruals_aggregate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _ACCRUALSAGGREGATE._serialized_start=35
  _ACCRUALSAGGREGATE._serialized_end=262
# @@protoc_insertion_point(module_scope)
