# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/contract.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dictum_proto.google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from dictum_proto.proto import entity_pb2 as proto_dot_entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/contract.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12proto/entity.proto\"\xbc\x01\n\x08\x43ontract\x12\x13\n\x0b\x63ontract_id\x18\x01 \x01(\x05\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x10\n\x08payer_id\x18\x03 \x01(\x05\x12\x14\n\x0crecipient_id\x18\x04 \x01(\x05\x12/\n\x0b\x63reate_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x05payer\x18\x06 \x01(\x0b\x32\x07.Entity\x12\x1a\n\trecipient\x18\x07 \x01(\x0b\x32\x07.EntityB&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.contract_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _CONTRACT._serialized_start=78
  _CONTRACT._serialized_end=266
# @@protoc_insertion_point(module_scope)
