# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/currency_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/currency_type.proto*[\n\x0c\x43urrencyType\x12\x19\n\x15\x43URRENCY_TYPE_UNKNOWN\x10\x00\x12\x18\n\x14\x43URRENCY_TYPE_CRYPTO\x10\x01\x12\x16\n\x12\x43URRENCY_TYPE_FIAT\x10\x02\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.currency_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _CURRENCYTYPE._serialized_start=29
  _CURRENCYTYPE._serialized_end=120
# @@protoc_insertion_point(module_scope)
