# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service_run_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/service_run_state.proto*\x8e\x01\n\x0fServiceRunState\x12\x1d\n\x19SERVICE_RUN_STATE_UNKNOWN\x10\x00\x12\x1d\n\x19SERVICE_RUN_STATE_RUNNING\x10\x01\x12\x1f\n\x1bSERVICE_RUN_STATE_COMPLETED\x10\x02\x12\x1c\n\x18SERVICE_RUN_STATE_FAILED\x10\x03\x42&Z$github.com/AlexKenbo/dictum_proto/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_run_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z$github.com/AlexKenbo/dictum_proto/go'
  _SERVICERUNSTATE._serialized_start=34
  _SERVICERUNSTATE._serialized_end=176
# @@protoc_insertion_point(module_scope)
